### Linear algebra basics

In [2]:
import numpy as np

In [12]:
x = np.array([3, 4, 1]); x

array([3, 4, 1])

In [13]:
y = np.array([2, -3, 4]); y 

array([ 2, -3,  4])

#### Dot product

In [5]:
np.dot(x, y)

-2

In [4]:
x = np.array([1, 2, 3])
y = np.array([2, -4, 8])

In [10]:
np.dot(x, y)

18

Angle between two vectors: 

$\cos(\theta) = \frac{x \cdot y}{|x||y|}$

In [14]:
np.dot(x, y)/(np.linalg.norm(x) * np.linalg.norm(y))

-0.07283570407292297

In [15]:
np.dot(x, y)/(np.sqrt(9 + 16 + 1) * np.sqrt(4 + 9 + 16))

-0.07283570407292297

#### Matrix multiplication

In [19]:
A = np.array([[1, -2, 1], [2, -4, 5]]); A

array([[ 1, -2,  1],
       [ 2, -4,  5]])

In [8]:
B = np.array([[3, 4, 2], [1, -2, 0], [2, 1, -3]]); B

array([[ 3,  4,  2],
       [ 1, -2,  0],
       [ 2,  1, -3]])

In [9]:
np.matmul(A, B)

array([[  3,   9,  -1],
       [ 12,  21, -11]])

**Note:** Matrix multiplication is not commutative  
AB ≠ BA

#### Transpose

In [16]:
AT = A.transpose(); AT

array([[ 1,  2],
       [-2, -4],
       [ 1,  5]])

$(AB)^T = B^T A^T$

In [17]:
(np.matmul(A, B)).transpose()

array([[  3,  12],
       [  9,  21],
       [ -1, -11]])

In [18]:
np.matmul(B.transpose(), A.transpose())

array([[  3,  12],
       [  9,  21],
       [ -1, -11]])

$u, v~\epsilon~\text{R}^d$, $u \cdot v = u^T v$

In [19]:
u = np.array([3, 4, 1]); u

array([3, 4, 1])

In [20]:
v = np.array([1, 5, 3]); v

array([1, 5, 3])

In [21]:
np.matmul(u.transpose(), v)

26

In [22]:
np.dot(u, v)

26

#### Symmetric matrix

$M = M^T$ 

Diagonal matrices are always symmetric.

#### Determinant

A = [a b; c d] 

det(A) = ad - bc

Determinant of a diagonal matrix is the product of diagonal elements.

#### Inverse 

AB = BA = I  

B is inverse of A. (A is a square matrix)

$B = A^{-1}$ 

A matrix for which inverse does not exist is called singular matrix. 

A is invertible if and only if |A| ≠ 0

In [23]:
A = np.array([[1, 2, 4], [-2, 0, 3], [5, -1, -2]]); A

array([[ 1,  2,  4],
       [-2,  0,  3],
       [ 5, -1, -2]])

In [24]:
np.linalg.det(A)

33.000000000000014

In [25]:
np.linalg.inv(A)

array([[ 9.09090909e-02, -2.22044605e-17,  1.81818182e-01],
       [ 3.33333333e-01, -6.66666667e-01, -3.33333333e-01],
       [ 6.06060606e-02,  3.33333333e-01,  1.21212121e-01]])