In [1]:
import numpy as np
my_array = np.array([1, 3, 4])
print(my_array)

[1 3 4]


In [2]:
type(my_array)

numpy.ndarray

In [3]:
my_array2 = np.array([[1, 2, 4], [3, 1, 5]])
print(my_array2)

[[1 2 4]
 [3 1 5]]


In [4]:
my_array2.ndim

2

In [5]:
my_array2.shape

(2, 3)

In [6]:
my_array2.size

6

In [7]:
my_array2.dtype

dtype('int64')

In [8]:
my_array3 = np.array([[1, 4, 7], [1, 9, 32]], dtype=np.float64)
my_array3.dtype

dtype('float64')

In [9]:
my_array3.astype(np.int64)

array([[ 1,  4,  7],
       [ 1,  9, 32]])

In [10]:
my_array3 = np.array(my_array3, dtype=np.float64)
print(my_array3)

[[ 1.  4.  7.]
 [ 1.  9. 32.]]


In [11]:
my_zero_array = np.zeros((2, 3))
print(my_zero_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
my_ones_array = np.ones((2, 3))
print(my_ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
my_const_array = np.full([2, 3], 5)
print(my_const_array)

[[5 5 5]
 [5 5 5]]


In [14]:
my_array4 = np.arange(1, 10, 2)
print(my_array4)

[1 3 5 7 9]


In [15]:
my_array5 = np.linspace(1, 10, 10)
print(my_array5)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [16]:
x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])

X, Y = np.meshgrid(x, y)
print(X, '\n\n', Y)

[[-1  0  1]
 [-1  0  1]
 [-1  0  1]] 

 [[-2 -2 -2]
 [ 0  0  0]
 [ 2  2  2]]


In [17]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [20]:
np.eye(4, k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [21]:
np.diag(np.arange(0, 20, 5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [22]:
np.random.rand(3)

array([0.96165097, 0.5679946 , 0.1614081 ])

In [23]:
np.random.rand(2, 3)

array([[0.55184819, 0.4654899 , 0.43385936],
       [0.38086648, 0.44093323, 0.0956264 ]])

In [24]:
my_array_10 = np.random.randn(5); my_array_10

array([-0.25214049, -1.20321087,  0.15403658,  0.51131407, -2.44165102])